/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qkd;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author waltersquires
 */
public class Constructor extends javax.swing.JPanel {
    GUI holder;

    /**
     * Creates new form Constructor
     */
    public Constructor() {
        initComponents();
    }
    
     public void setMaker(GUI maker)
    {
        holder = maker;  
    }

    public void addDensityList(DensityListRepresentation x)
    {
        densityLists.add(x);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        densityLists = new javax.swing.JTabbedPane();
        buttonPanel = new javax.swing.JPanel();
        newListButton = new javax.swing.JButton();
        saveAndQuitButton = new javax.swing.JButton();
        visualizeButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(densityLists);

        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.LINE_AXIS));

        newListButton.setText("Add New Density List");
        newListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newListButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(newListButton);

        saveAndQuitButton.setText("Save & Quit");
        saveAndQuitButton.setMaximumSize(new java.awt.Dimension(100, 30));
        saveAndQuitButton.setPreferredSize(new java.awt.Dimension(100, 30));
        saveAndQuitButton.setSize(new java.awt.Dimension(100, 30));
        saveAndQuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndQuitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveAndQuitButton);

        visualizeButton.setText("Visualize");
        visualizeButton.setMaximumSize(new java.awt.Dimension(100, 30));
        visualizeButton.setPreferredSize(new java.awt.Dimension(100, 30));
        visualizeButton.setSize(new java.awt.Dimension(100, 30));
        buttonPanel.add(visualizeButton);

        testButton.setText("Test");
        testButton.setMaximumSize(new java.awt.Dimension(100, 30));
        testButton.setPreferredSize(new java.awt.Dimension(100, 30));
        testButton.setSize(new java.awt.Dimension(100, 30));
        buttonPanel.add(testButton);

        add(buttonPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void saveAndQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndQuitButtonActionPerformed
        
//        Marie Additions
        
        JFileChooser fc;
        int i = densityLists.getTabCount();
        for(int j=0; j<i;j++)
        {
            fc = new JFileChooser();
             int user_decision;
             user_decision = fc.showSaveDialog(Constructor.this);
             if (user_decision == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
             }
        }
        
//        End Marie Additions

        densityLists.removeAll();
        holder.displayMain();
    }//GEN-LAST:event_saveAndQuitButtonActionPerformed

    private void newListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newListButtonActionPerformed
DensityListRepresentation temp = new DensityListRepresentation();
int i = densityLists.getTabCount();
addDensityList(temp);

densityLists.setTitleAt(i++, temp.getName());
    }//GEN-LAST:event_newListButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JTabbedPane densityLists;
    private javax.swing.JButton newListButton;
    private javax.swing.JButton saveAndQuitButton;
    private javax.swing.JButton testButton;
    private javax.swing.JButton visualizeButton;
    // End of variables declaration//GEN-END:variables
}
